namespace KlaviyoSharp.Models;

public class ClientProfileRequestAttributes : AttributesObject
{
    /// <summary>
    /// Primary key that uniquely identifies this profile. Generated by Klaviyo.
    /// </summary>
    string id { get; set; }
    /// <summary>
    /// Individual's email address
    /// </summary>
    string email { get; set; }
    /// <summary>
    /// Individual's phone number in E.164 format
    /// </summary>
    string phone_number { get; set; }
    /// <summary>
    /// A unique identifier used by customers to associate Klaviyo profiles with profiles in an external system, such as a point-of-sale system.
    /// Format varies based on the external system.
    /// </summary>
    string external_id { get; set; }
    string anonymous_id { get; set; }
    /// <summary>
    /// Also known as the exchange_id, this is an encrypted identifier used for identifying a profile by Klaviyo's web tracking.
    /// You can use this field as a filter when retrieving profiles via the Get Profiles endpoint.
    /// </summary>
    string _kx { get; set; }
    string first_name { get; set; }
    /// <summary>
    /// Individual's first name
    /// </summary>
    string last_name { get; set; }
    /// <summary>
    /// Individual's last name
    /// </summary>
    string organization { get; set; }
    /// <summary>
    /// Name of the company or organization within the company for whom the individual works
    /// </summary>
    string title { get; set; }
    /// <summary>
    /// Individual's job title
    /// </summary>
    string image { get; set; }
    /// <summary>
    /// URL pointing to the location of a profile image
    /// </summary>
    Location location { get; set; }
}