using Newtonsoft.Json;

namespace KlaviyoSharp.Models;

public class ClientProfileRequestAttributes : AttributesObject
{
    /// <summary>
    /// Primary key that uniquely identifies this profile. Generated by Klaviyo.
    /// </summary>
    [JsonProperty("id")]
    public string Id { get; set; }
    /// <summary>
    /// Individual's email address
    /// </summary>
    [JsonProperty("email")]
    public string Email { get; set; }
    /// <summary>
    /// Individual's phone number in E.164 format
    /// </summary>
    [JsonProperty("phone_number")]
    public string PhoneNumber { get; set; }
    /// <summary>
    /// A unique identifier used by customers to associate Klaviyo profiles with profiles in an external system, such as a point-of-sale system.
    /// Format varies based on the external system.
    /// </summary>
    [JsonProperty("external_id")]
    public string ExternalId { get; set; }
    /// <summary>
    /// Undocumented
    /// </summary>
    [JsonProperty("anonymous_id")]
    public string AnonymousId { get; set; }
    /// <summary>
    /// Also known as the exchange_id, this is an encrypted identifier used for identifying a profile by Klaviyo's web tracking.
    /// You can use this field as a filter when retrieving profiles via the Get Profiles endpoint.
    /// </summary>
    [JsonProperty("_kx")]
    public string Kx { get; set; }
    /// <summary>
    /// Individual's first name
    /// </summary>
    [JsonProperty("first_name")]
    public string FirstName { get; set; }
    /// <summary>
    /// Individual's last name
    /// </summary>
    [JsonProperty("last_name")]
    public string LastName { get; set; }
    /// <summary>
    /// Name of the company or organization within the company for whom the individual works
    /// </summary>
    [JsonProperty("organization")]
    public string Organization { get; set; }
    /// <summary>
    /// Individual's job title
    /// </summary>
    [JsonProperty("title")]
    public string Title { get; set; }
    /// <summary>
    /// URL pointing to the location of a profile image
    /// </summary>
    [JsonProperty("image")]
    public string ImageUrl { get; set; }
    /// <summary>
    ///
    /// </summary>
    [JsonProperty("location")]
    public Location Location { get; set; }
}