using System;
using System.Collections.Generic;
using Newtonsoft.Json;

namespace KlaviyoSharp.Models;

public class ClientProfile : KlaviyoObjectBasic<ClientProfileAttributes>
{
    public static new ClientProfile Create()
    {
        return new() { Type = "profile" };
    }
}
public class ClientProfileAttributes
{
    /// <summary>
    /// Primary key that uniquely identifies this profile. Generated by Klaviyo.
    /// </summary>
    [JsonProperty("id")]
    public string Id { get; set; }
    /// <summary>
    /// Individual's email address
    /// </summary>
    [JsonProperty("email")]
    public string Email { get; set; }
    /// <summary>
    /// Individual's phone number in E.164 format
    /// </summary>
    [JsonProperty("phone_number")]
    public string PhoneNumber { get; set; }
    /// <summary>
    /// A unique identifier used by customers to associate Klaviyo profiles with profiles in an external system, such as a point-of-sale system.
    /// Format varies based on the external system.
    /// </summary>
    [JsonProperty("external_id")]
    public string ExternalId { get; set; }
    /// <summary>
    /// Undocumented
    /// </summary>
    [JsonProperty("anonymous_id")]
    public string AnonymousId { get; set; }
    /// <summary>
    /// Also known as the exchange_id, this is an encrypted identifier used for identifying a profile by Klaviyo's web tracking.
    /// You can use this field as a filter when retrieving profiles via the Get Profiles endpoint.
    /// </summary>
    [JsonProperty("_kx")]
    public string Kx { get; set; }
    /// <summary>
    /// Individual's first name
    /// </summary>
    [JsonProperty("first_name")]
    public string FirstName { get; set; }
    /// <summary>
    /// Individual's last name
    /// </summary>
    [JsonProperty("last_name")]
    public string LastName { get; set; }
    /// <summary>
    /// Name of the company or organization within the company for whom the individual works
    /// </summary>
    [JsonProperty("organization")]
    public string Organization { get; set; }
    /// <summary>
    /// Individual's job title
    /// </summary>
    [JsonProperty("title")]
    public string Title { get; set; }
    /// <summary>
    /// URL pointing to the location of a profile image
    /// </summary>
    [JsonProperty("image")]
    public string ImageUrl { get; set; }
    /// <summary>
    ///
    /// </summary>
    [JsonProperty("location")]
    public ClientProfileLocation Location { get; set; }

    /// <summary>
    /// An object containing key/value pairs for any custom properties assigned to this profile
    /// </summary>
    [JsonProperty("properties")]
    public Dictionary<string, object> Properties { get; set; }
}

public class ClientProfileLocation
{
    /// <summary>
    /// First line of street address
    /// </summary>
    [JsonProperty("address1")]
    public string Address1 { get; set; }
    /// <summary>
    /// First line of street address
    /// </summary>
    [JsonProperty("address2")]
    public string Address2 { get; set; }
    /// <summary>
    /// City name
    /// </summary>
    [JsonProperty("city")]
    public string City { get; set; }
    /// <summary>
    /// Country name
    /// </summary>
    [JsonProperty("country")]
    public string Country { get; set; }
    /// <summary>
    /// Latitude coordinate. We recommend providing a precision of four decimal places.
    /// </summary>
    [JsonProperty("latitude")]
    public double? Latitude { get; set; }
    /// <summary>
    /// Longitude coordinate. We recommend providing a precision of four decimal places.
    /// </summary>
    [JsonProperty("longitude")]
    public double? Longitude { get; set; }
    /// <summary>
    /// Region within a country, such as state or province
    /// </summary>
    [JsonProperty("region")]
    public string Region { get; set; }
    /// <summary>
    /// Zip code
    /// </summary>
    [JsonProperty("zip")]
    public string Zip { get; set; }
    /// <summary>
    /// Time zone name. We recommend using time zones from the IANA Time Zone Database.
    /// </summary>
    [JsonProperty("timezone")]
    public string Timezone { get; set; }
}